Repository cloud-native-toolkit/terraform-provider-gitops, pull requests merged in 2022-11, with the labels that each got.

#54 Adds gitops_repo resource
  examples/provider-resources/main.tf
  examples/provider-resources/variables.tf
  examples/stage1-gitops.tf
  examples/stage2-namespace.tf
  examples/stage3-mymodule.tf
  gitops/provider.go
  gitops/resource_gitops_repo.go
Labels: minor, feature

#66 Updates version to 0.10.0
  Makefile
Labels: patch, chore

#67 Reads gitops-init command results from jsonfile
  gitops/resource_gitops_repo.go
Labels: bug, patch

#68 Updates version to 0.10.1
  Makefile
Labels: patch, chore

#69 Adds debug logging for gitops repo resource
  gitops/resource_gitops_repo.go
Labels: bug, patch

#70 Updates version to 0.10.2
  Makefile
Labels: patch, chore

#71 Updates configuration options on provider
  examples/provider.tf
  examples/stage1-gitops.tf
  examples/stage2-namespace.tf
  examples/stage3-mymodule.tf
  gitops/provider.go
  gitops/resource_gitops_module.go
  gitops/resource_gitops_namespace.go
  gitops/resource_gitops_pull_secret.go
  gitops/resource_gitops_repo.go
  gitops/resource_gitops_service_account.go
Labels: minor, feature

#72 Updates version to 0.11.0
  Makefile
Labels: patch, chore

#75 Updates version to 0.11.1
  Makefile
Labels: patch, chore
