Repository cloud-native-toolkit/terraform-provider-gitops, pull requests merged in 2022-10, with the labels that each got.

#57 Adds support for ignoreDiff argument to GitOps config
  gitops/helpers.go
  gitops/resource_gitops_module.go
  gitops/resource_gitops_service_account.go
Labels: minor, feature

#59 Adds support for pull secrets on service accounts
  examples/provider-resources/main.tf
  gitops/resource_gitops_service_account.go
Labels: minor, feature

#61 Updates version to 0.9.0
  Makefile
Labels: patch, chore

#62 Updates service-account chart to v1.2.1 to fix issue
  gitops/resource_gitops_service_account.go
Labels: bug, patch

#63 Updates version to 0.9.1
  Makefile
Labels: patch, chore

#64 Updates namespace helm chart to v0.2.0
  gitops/resource_gitops_namespace.go
Labels: bug, patch

#65 Updates version to 0.9.2
  Makefile
Labels: patch, chore
