Repository cloud-native-toolkit/terraform-provider-gitops, pull requests merged in 2022-09, with the labels that each got.

#12 Fixes ca_cert and debug flags for destroy and adds value_files
  gitops/resource_gitops_module.go
  gitops/resource_gitops_namespace.go
Labels: bug, patch

#13 Adds logging and error handling for namespace resource
  gitops/resource_gitops_module.go
Labels: bug, patch

#14 Updates logging
  gitops/resource_gitops_module.go
  gitops/resource_gitops_namespace.go
Labels: bug, patch

#15 Fixes import
  gitops/resource_gitops_namespace.go
Labels: bug, patch

#16 Updates argument handling for igc commands
  gitops/resource_gitops_module.go
  gitops/resource_gitops_namespace.go
Labels: patch, chore

#19 Prints error message on failure
  docs/index.md
  gitops/resource_gitops_module.go
  gitops/resource_gitops_namespace.go
Labels: bug, patch

#20 updated handling of stderr for namespaces
  gitops/resource_gitops_namespace.go
Labels: bug, minor

#21 Fixes destroy logic
  .github/scripts/validate-deploy.sh
  .github/scripts/validation-functions.sh
  .github/workflows/verify-pr.yaml
  .github/workflows/verify.yaml
  .gitignore
  Makefile
  examples/.gitignore
  examples/apply.sh
  examples/destroy.sh
  examples/main.tf
  examples/provider.tf
  examples/reset.sh
  examples/stage1-gitops.tf
  examples/stage2-namespace.tf
  examples/variables.tf
  gitops/resource_gitops_module.go
  gitops/resource_gitops_namespace.go
Labels: patch, chore

#22 Fixes auto-tag logic
  .github/workflows/verify.yaml
  Makefile
Labels: patch, chore

#23 Updates logic used to set version in Makefile
  .github/workflows/verify.yaml
  Makefile
Labels: patch, chore

#24 Adds updated Makefile to commit
  .github/workflows/verify.yaml
Labels: patch, chore

#25 Adds logic to create and automerge PR
  .github/workflows/verify.yaml
  Makefile
Labels: patch, chore

#26 Updates version to 0.2.10
  Makefile
Labels: patch, chore

#29 Updates version to 0.2.11
  Makefile
Labels: patch, chore

#30 Initializes command env to os.Environ()
  .github/workflows/verify-pr.yaml
  gitops/resource_gitops_module.go
  gitops/resource_gitops_namespace.go
Labels: bug, patch

#31 Updates version to 0.2.12
  Makefile
Labels: patch, chore

#28 Updates test to use actual modules
  .github/scripts/validate-deploy.sh
  examples/gitops_module/main.tf
  examples/gitops_module/variables.tf
  examples/gitops_module/yaml/mymodule.yaml
  examples/gitops_namespace/main.tf
  examples/gitops_namespace/outputs.tf
  examples/gitops_namespace/variables.tf
  examples/gitops_namespace/yaml/ns.yaml
  examples/stage1-gitops.tf
  examples/stage2-namespace.tf
  examples/stage3-mymodule.tf
Labels: patch, chore

#32 Updates version to 0.2.13
  Makefile
Labels: patch, chore

#34 Adds enum validation for layer and type values
  gitops/resource_gitops_module.go
Labels: minor, feature

#35 Updates version to 0.3.0
  Makefile
Labels: patch, chore

#36 Updates namespace resource to support direct helm chart
  gitops/resource_gitops_module.go
  gitops/resource_gitops_namespace.go
Labels: minor, feature

#37 Updates version to 0.4.0
  Makefile
Labels: patch, chore

#38 Updates boolean input types to bool on namespace resource
  gitops/resource_gitops_namespace.go
Labels: bug, patch

#39 Updates version to 0.4.1
  Makefile
Labels: patch, chore

#40 Adds gitops_service_account resource to add serviceaccount, rbac, and/or sccs to the gitops repo
  .github/scripts/validate-deploy.sh
  .github/scripts/validation-functions.sh
  examples/provider-resources/main.tf
  examples/provider-resources/outputs.tf
  examples/provider-resources/variables.tf
  examples/provider-resources/version.tf
  examples/sav/stage3-mymodule.tf
  examples/stage2-namespace.tf
  gitops/provider.go
  gitops/resource_gitops_namespace.go
  gitops/resource_gitops_service_account.go
  go.mod
  go.sum
Labels: minor, feature

#41 Updates version to 0.5.0
  Makefile
Labels: patch, chore

#42 Adds seal_secrets resource
  .github/scripts/validate-deploy.sh
  examples/provider-resources/main.tf
  examples/provider-resources/outputs.tf
  examples/provider-resources/secrets/mysecret.yaml
  examples/provider-resources/variables.tf
  examples/stage2-namespace.tf
  examples/stage3-mymodule.tf
  gitops/provider.go
  gitops/resource_gitops_seal_secrets.go
  gitops/resource_gitops_service_account.go
Labels: minor, feature

#43 Updates version to 0.6.0
  Makefile
Labels: patch, chore

#44 Adds gitops_pull_secret resource
  .github/scripts/validate-deploy.sh
  Makefile
  docs/index.md
  docs/resources/module.md
  docs/resources/namespace.md
  docs/resources/pull_secret.md
  docs/resources/seal_secrets.md
  docs/resources/service_account.md
  examples/provider-resources/main.tf
  examples/provider.tf
  examples/version.tf
  gitops/helpers.go
  gitops/provider.go
  gitops/resource_gitops_module.go
  gitops/resource_gitops_pull_secret.go
  gitops/resource_gitops_seal_secrets.go
  gitops/resource_gitops_service_account.go
Labels: minor, feature

#45 Updates version to 0.7.0
  Makefile
Labels: patch, chore

#46 Cleans up service account resource logic
  .github/scripts/validate-deploy.sh
  docs/resources/service_account.md
  gitops/resource_gitops_service_account.go
Labels: patch, chore

#48 Updates version to 0.7.1
  Makefile
Labels: patch, chore

#49 Updates service-account helm chart to 1.0.1 to fix issue
  gitops/resource_gitops_service_account.go
Labels: bug, patch

#50 Updates version to 0.7.2
  Makefile
Labels: patch, chore

#51 Updates service-account chart to v1.1.0
  gitops/resource_gitops_service_account.go
Labels: patch, chore

#52 Updates version to 0.7.3
  Makefile
Labels: patch, chore
