Repository cloud-native-toolkit/terraform-provider-gitops, pull requests merged in 2023-06, with the labels that each got.

#78 Update provider logging
  .github/workflows/release.yml
  .github/workflows/verify-pr.yaml
  .github/workflows/verify.yaml
  gitops/provider.go
  go.mod
Labels: patch, chore

#79 Fix release workflow
  .github/workflows/verify.yaml
  README.md
Labels: bug, patch

#80 Updates version to 0.12.1
  Makefile
Labels: patch, chore

#81 Update version in Makefile
  Makefile
Labels: patch, chore

#82 Add resources and data sources for gitops metadata
  .github/workflows/verify-pr.yaml
  examples/provider-resources/main.tf
  examples/stage1-cluster.tf
  examples/stage2-metadata.tf
  examples/stage2-namespace.tf
  examples/variables.tf
  gitops/data_gitops_metadata_cluster.go
  gitops/data_gitops_metadata_packages.go
  gitops/helper_gitops_metadata.go
  gitops/helpers.go
  gitops/provider.go
  gitops/resource_gitops_metadata.go
  gitops/resource_gitops_repo.go
  gitops/resource_gitops_seal_secrets.go
  gitops/resource_gitops_service_account.go
  go.mod
  go.sum
Labels: minor, feature

#83 Updates version to 0.13.0
  Makefile
Labels: patch, chore

#84 Add data source to get gitops config
  examples/stage1-gitops.tf
  gitops/data_gitops_repo_config.go
  gitops/provider.go
Labels: minor, feature

#85 Updates version to 0.14.0
  Makefile
Labels: patch, chore

#86 Support passing url to gitops_repo resource
  gitops/resource_gitops_repo.go
Labels: minor, feature

#87 Updates version to 0.15.0
  Makefile
Labels: patch, chore

#88 Remove repo as required field for gitops_repo resource
  gitops/resource_gitops_repo.go
Labels: bug, patch

#89 Updates version to 0.15.1
  Makefile
Labels: patch, chore

#90 Mask credentials from environment logging
  gitops/data_gitops_repo_config.go
  gitops/helper_gitops_metadata.go
  gitops/helpers.go
  gitops/resource_gitops_metadata.go
  gitops/resource_gitops_module.go
  gitops/resource_gitops_namespace.go
  gitops/resource_gitops_repo.go
Labels: bug, patch

#91 Updates version to 0.15.2
  Makefile
Labels: patch, chore
